version: '3'

networks:
  nginx-php81:

services:

  # nginx
  nginx-service:
    image: nginx:stable-alpine
    container_name: nginx-container
    ports:
      - "80:80"
    volumes:
      - .:/var/www/project
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php81-service
    networks:
      - nginx-php81

  # php
  php81-service:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: php81-container
    ports:
      - "9000:9000"
    volumes:
      - .:/var/www/project
    networks:
      - nginx-php81
